name: Import Code-signing Certificates

on:
  push:
    branches:
      - master

jobs:
  import-certificates:
    runs-on: macos-latest
    steps:
      - name: Import Certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.DEV_ID_APP_CERT }}
          p12-password: ${{ secrets.DEV_ID_APP_PASSWORD }}
